### ISSUE TITLE
Add html input  

### ISSUE THREAD

**Issue by iamheiner** [MTobisch/ngx-dynamic-hooks#1]
Is it possible to add input tags to your content?

I'm trying the following but it doesn't show me the input tags

      
>
   
    <p>Let's load a dynamic component here: <app-example></app-example></p>
    <p>How about a component for an image:</p>   

    ==>  <input>  

    <app-image [src]="'https://i.imgur.com/3Hvh6lx.jpg'">
    <b>or a text-box:</b>
    <app-box [backgroundColor]="'#4493ff40'">
      with projected contentkk!
    </app-box>

Is it possible that I am doing something wrong?

Thank you

**Comment by MTobisch** [comment]
Hi Heiner,

It is possible, but you would have to disable sanitization for that.

Here is a working example: https://stackblitz.com/edit/ngx-dynamic-hooks-quickstart-with-input. Take a look into app.component.html where sanitization has been disabled in the “options” input.

Sanitization is enabled by default to prevent potentially dangerous code from being rendered, like <script>-tags and such. The library uses Angular’s own DomSanitizer to do so, which is fairly aggressive and also removes all kinds of other stuff (input-tags as well :-]).

So just disable it if it gets in the way. But then do make sure that the content you are rendering is safe and doesn’t contain malicious code!

All the best,
Marvin
