### ISSUE TITLE
About loading components depending on a JSON response from API

### ISSUE THREAD

**Issue by guihgs** [MTobisch/ngx-dynamic-hooks#10]
Hi is more of a question about using the dynamic hooks to load component that expecting a response from a rest api.
How can I load this components in the same order that the json brings this data

**Comment by MTobisch** [comment]
I'm sorry, I'm having a hard time understanding what it is you are trying to do. Maybe you could clarify a bit?

If you just want to render components as they are listed in in a JSON, you could simply put them in an array and loop it in a template via ngFor and render <ngx-dynamic-hooks> for each component. 

You could also loop that array before rendering and create a single string filled with one component selector after the other like "<app-componentX></app-componentX><app-componentY></app-componentY>..." and simply hand that string to a single <ngx-dynamic-hooks>-component.
