### ISSUE TITLE
Question: CSS in template

### ISSUE THREAD

**Issue by ppkh** [MTobisch/ngx-dynamic-hooks#15]
Hello Friends

Is there a way to define CSS klasses inside e.g. a <style> tag and use the classes and styles directly in the template?

Imagining something like this:

```
<style>
   .myClass {
        background-color: 'red';
    }
</style>
<div class="myClass">A div container</div>
```

I tried this and the style tags gets spliced and then not recognized. Or is it something we can already configure?

**Comment by MTobisch** [comment]
Hey there!

The style tags are removed by the `sanitize`-option, which is enabled by default and meant to protect against injecting malicious code (<script>-tags are also removed).

You can disable it by passing a different [OutletOptions](https://github.com/MTobisch/ngx-dynamic-hooks#64-outletoptions) object to the `OutletComponent` or in the global settings such as `{sanitize: false}`.

**Comment by ppkh** [comment]
Hi @MTobisch, thanks for the quick reply and providing the right spot!
I tried it and it works now.
