### ISSUE TITLE
Update rxjs version to 7 for use in angular 13

### ISSUE THREAD

**Issue by hhiliahh** [MTobisch/ngx-dynamic-hooks#16]
thanks.

**Comment by MTobisch** [comment]
Hey there, I've just released version 2.0.0 of the library for rxjs 7 and Angular 13!

To jump to 2.0.0 is not a breaking update per se, but I can't guarantee stability for Angular versions under 13 and rxjs under 7 as I've taken the opportunity to update a lot of dependencies and the way the library is built. 

So going forward, people can just use v2.0.0 for Angular 13+, and older versions of the library for Angular 12 and below :-]

**Comment by hhiliahh** [comment]
thanks.
