### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by ilkerkoc** [MTobisch/ngx-dynamic-hooks#22]
Hi. 

Angular 14 is out. 

When I try to update npm giving  dependency errors.

>npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^13" from ngx-dynamic-hooks@2.0.2
npm ERR! node_modules/ngx-dynamic-hooks
npm ERR!   ngx-dynamic-hooks@"2.0.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@13.3.11
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"^13" from ngx-dynamic-hooks@2.0.2
npm ERR!   node_modules/ngx-dynamic-hooks
npm ERR!     ngx-dynamic-hooks@"2.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

For now I am using --force parameter. When can we get an update.

Thank you.

**Comment by MTobisch** [comment]
Hey there!

The library now supports Angular 14 with v2.0.3. This should work now without `--force`:

`npm install ngx-dynamic-hooks@2.0.3`
