### ISSUE TITLE
reference variables for viewChild components

### ISSUE THREAD

**Issue by sharsmita** [MTobisch/ngx-dynamic-hooks#25]
Hi,
I'm trying to render a component in a dynamic html. The component is referenced as viewchild in parent component, so needs reference variable something like this
<p>lets get the map here</p> <app-map #mapElement></app-map> 

The hookparser throws error 
Syntax error - Closing tag without preceding opening tag found: "</app-map>". Ignoring.

I've set santize to false. 
Please let me know the correct way of doing this.

thanks

**Comment by MTobisch** [comment]
Hey there,

there seems to be two issues at play here, though I'm not 100% I understand your issue correctly.

1. Assuming this hierarchy: "`ParentComponent` > `ngx-dynamic-hooks` > `DynamicallyCreatedComponents`", you cannot directly reference the `DynamicallyCreatedComponents` as ViewChildren from `ParentComponent`. After all, the `ngx-dynamic-hooks` component is in the way. However, you can subscribe to the "[componentsLoaded-output](https://github.com/MTobisch/ngx-dynamic-hooks#62-outlet-component-bindings)" of `ngx-dynamic-hooks` to get a list of them anyway. Like so:
```
<ngx-dynamic-hooks [content]="'dynamicContent'" (componentsLoaded)="dynamicComponents = $event"></ngx-dynamic-hooks>
``` 
2. The other issue is the syntax error. This shouldn't have anything to do with the ViewChildren problem. It just means what is says: That the closing hook of a component was found before an opening hook was found. The weird thing in the error is that he apparently thinks that the closing tag is simply an empty string (so of course he's going to find that immediately). But it should be filled out with an actual string. Do you use a custom hook parser, perhaps? Of some custom config? If you could post these, I might be able to troubleshoot this further.

**Comment by sharsmita** [comment]
Thanks for replying.
The syntax error is due to the fact that it matches the opening and closing tags exactly. so an element like 
 ` < app-map #mapElement ></ app-map >`
throws error, but 
` <app-map ></app-map>`
does not. So the child component is rendered but does no work.
I get what you are saying in the first point, if you have an example of how to reference componentsLoaded in parent component that will solve my problem I guess.
Thanks

**Comment by MTobisch** [comment]
Ah, yeah that would make sense why he can't find the opening tag then! The hashtag would really confuse him with a standard config.

And getting the loaded components in the parent component is quite easy. I've already postet half the code. So your parent component could basically look like this:

**parentComponent.c.ts**
```
import { LoadedComponent } from 'ngx-dynamic-hooks';

FilterControlStaticComponent implements OnInit, OnChanges, AfterViewInit, OnDestroy {
  dynamicContent: string = 'this is some text with the component <app-map></app-map>'
  dynamicComponents: LoadedComponent[];
  ...
}
```

**parentComponent.c.html**
```
<ngx-dynamic-hooks [content]="'dynamicContent'" (componentsLoaded)="dynamicComponents = $event"></ngx-dynamic-hooks>
```

Once initialized, `loadedComponents` will then be an array of all the found dynamic components, with the form

```
interface LoadedComponent {
    hookId: number;                     // The unique hook id
    hookValue: HookValue;               // The hook that was replaced by this component
    hookParser: HookParser;             // The associated parser
    componentRef: ComponentRef<any>;    // The created componentRef
}
```

In this example, it would only contain the one `<app-map>`-component, and you're probably just interested in its `componentRef`.
