### ISSUE TITLE
ng-template support

### ISSUE THREAD

**Issue by Marc-Schuster** [MTobisch/ngx-dynamic-hooks#26]
Hi, 
i would like to know if it would be possible to somehow dynamically insert ng-template via dynamic hooks?
Thank you in advance.

**Comment by MTobisch** [comment]
Hey there,

if you are trying to use ng-template/ng-container in the content string, you can't, unfortunately. These are Angular template syntax features (much like ngIf, ngFor, etc.) and therefore won't work. Under the hood, this library is rather simple and really just parses the content string for component selectors and nothing else.

Depending on what you are trying to do, however, there may be other ways to achieve the desired result. You could swap out the whole content string with a version that uses a different template to rerender everything (not exactly efficient). 

Or you could perhaps write a simple custom ng-container component that is loaded as a dynamic hook and that accepts the template as a string input (you could pass it in [via the context object](https://github.com/MTobisch/ngx-dynamic-hooks#5-features)). Then in that component, have another nested `<ngx-dynamic-hooks>`-component that just renders this "template". Changing the template in the context object would then automatically just rerender that specific part.
