### ISSUE TITLE
Print stacktrace instead of message when component could not be loaded

### ISSUE THREAD

**Issue by fleskberg** [MTobisch/ngx-dynamic-hooks#28]
Hi!
When a component could not be loaded I would like to have a stacktrace instead of just the message. To easily find where the problem is.
![image](https://user-images.githubusercontent.com/102948101/218450389-62b07d9f-595f-424f-9a98-93e9641a442e.png)

**Comment by MTobisch** [comment]
Hey there,

sure, I made it so that it now prints the stack trace in the new version.

**Angular 6-13:** ngx-dynamic-hooks 1.7.5
**Angular 13+:** ngx-dynamic-hooks 2.0.5

Hope this helps!

**Comment by fleskberg** [comment]
Hi! Thanks for a quick response. Got a stacktrace exactly as I wanted it. Thank you!
