### ISSUE TITLE
Understanding content projection and contentChildren array of length 0

### ISSUE THREAD

**Issue by lmenou** [MTobisch/ngx-dynamic-hooks#31]
Hi!
Thank you very much for your work on this very cool library, I like this idea!

I have just tried to use nested dynamic components and I have a hard time to understand them. It is more than possible that I do not use them properly as I am experimenting the very same problem spotted in #6 (I did not see any ref to a stackblitz though, that is why I am opening that issue). 

I tried to do something very basic, loading components from a database:

I have an implementation for `app-parent` component:
```typescript
@Component({
    selector: 'app-parent',
    template: '<p>hi!</p>',
})
export class MasterFormComponent implements OnInit, OnDynamicMount {

    ngOnInit(): void {}

    onDynamicMount(data: OnDynamicData): void {
        console.log(data.contentChildren);
    }
}
```

I also have an implementation of a child component `app-content-child`:
```typescript
@Component({
    selector: 'app-content-child',
    template: '<p>{{ paragraph }}</p>',
})
export class InputTextComponent implements OnInit {
    paragraph: string = 'hello!';

    ngOnInit(): void {}
}
```

However, when writing the view:
```html
<app-parent>
    <app-content-child></app-content-child>
</app-parent>
```
I have an `Array` of length 0 logged into the console. Did I misunderstand something in the nesting ?
I am sorry for the duplicate and the annoyance if any.

angular version: 14.2
ngx-dynamic-hook: 2.0.3

**Comment by MTobisch** [comment]
Hello there!

No worries, I'm always happy to help people using the library.

I think in your example, you might have forgotten to put an `<ng-content>` element into the parent component. So I would assume he does not even render the content child component.

In the parent component, if you change the template from `<p>hi!</p>` to `<p>hi!</p><ng-content></ng-content>`, it should work.

**Comment by lmenou** [comment]
You are absolutely right ! I somehow misinterpreted how to use <ng-content> properly.
Thank you very much for your time and for the very quick answer (and for adding a note in the readme ;) ) !
