### ISSUE TITLE
A hook with the same position as another hook was found

### ISSUE THREAD

**Issue by knight3000** [MTobisch/ngx-dynamic-hooks#33]
Hi there,

I'm coming across these warnings when added adding multiple components within the same hook. 

![image](https://github.com/MTobisch/ngx-dynamic-hooks/assets/12738683/94f3458e-3652-4c38-9391-38e0a77e64bf)

I have an angular library of components that I created. Using angular elements I turn them into web components. One of the components is using the dynamic hooks.  I'm trying to set an event listener on one of the buttons that is rendered by the hook, however the listener is not working. I wasn't sure if those warnings has something to do with it. Any ideas?

Here is my code 

**module.ts**

import { NgModule } from '@angular/core';
import { KrakenWebMastheadComponent } from './kraken-web-masthead.component';
import { CommonModule } from '@angular/common';
import { KrakenMastheadModule,  } from 'kraken-masthead';
import { KrakenButtonComponent, KrakenButtonModule } from 'kraken-button';
import { DynamicHooksModule, HookParserEntry } from 'ngx-dynamic-hooks';
import { KrakenToggleComponent, KrakenToggleModule } from 'kraken-toggle'
import { KrakenIconButtonComponent, KrakenIconButtonModule } from 'kraken-icon-button';
import { KrakenMenuButtonComponent, KrakenMenuButtonModule } from 'kraken-menu-button';
import { KrakenIconMenuModule, KrakenIconMenuComponent } from 'kraken-icon-menu';

const componentParsers: Array<HookParserEntry> = [
  {component: KrakenButtonComponent},
  {component: KrakenToggleComponent},
  {component: KrakenIconButtonComponent},
  {component: KrakenMenuButtonComponent},
  {component: KrakenIconMenuComponent}
];

@NgModule({
  declarations: [
    KrakenWebMastheadComponent
  ],
  imports: [
    CommonModule,
    KrakenMastheadModule,
    KrakenButtonModule,
    KrakenToggleModule,
    KrakenIconButtonModule,
    KrakenMenuButtonModule,
    KrakenIconMenuModule,
    DynamicHooksModule.forRoot({
      globalParsers: componentParsers
    })
  ],
  exports: [
    KrakenWebMastheadComponent
  ]
})
export class KrakenWebMastheadModule { }

**component.html**

`<kn-masthead`
`   [id]="id" `
`   (onOverflowMenuSelection)="clickEvent($event)">`
`   <div logo>`
 `    <ngx-dynamic-hooks [content]="logo" [context]="logoContext"></ngx-dynamic-hooks>`
`   </div>`
`   <div siteName>`
`     <ngx-dynamic-hooks [content]="version"></ngx-dynamic-hooks>`
`   </div>`
`   <div leftNav>`
`     <div class="kn-header-nav" *ngFor="let item of links">`
`     <a class="link" href="{{item.url}}">{{item.name}}</a>`
`     </div>`
`   </div>`
`   <div rightNav>`
`      <ngx-dynamic-hooks [content]="rightNav" [context]="rightNavContext"></ngx-dynamic-hooks>`
`   </div>`
`</kn-masthead>`

Here is the code from a standard html file which I'm using to interact with the web component. 
       //component reference
       `<kn-web-masthead id="sampleMasthead"></kn-web-masthead>`

        //create the instance and set the properties
        `let masthead = document.querySelector('#sampleMasthead');`
        `masthead.logo = `<img src='KrakenDS_Masthead_ProductLogo_Lighthouse.svg`>'`
        `masthead.siteName = 'Site name here';`
        `masthead.addEventListener('onOverflowMenuSelection', (e) => {
          window.location.href = e.detail.url;
        });`

        //this is using the dynamic hook to render the content
        masthead.rightNav = 
        `<kn-button 
          [buttonId]="'helpButton'" 
          [buttonType]="'kn-pill'" 
          [buttonText]="'Help'" 
          [buttonIconLeft]="'fa-regular fa-circle-question'">
        </kn-button>
        <i class="fa-solid fa-bell kn-icon kn-icon-sm"></i>
        <kn-icon-menu
          [icon]="'fa-solid fa-gear'"
          [dropdownRightAligned]="true"
          [items]="['Link 1','Link 2']"
          [dropdownCustomWidth]="'max-content'">
        </kn-icon-menu>
        <div class="kn-pipe"></div>
        <div class="initials">K N</div>
        <kn-icon-menu
          id="test"
          [id]="'initialsDropdown'"
          [icon]="'fa-regular fa-chevron-down'"
          [dropdownRightAligned]="true"
          [items]="['Link 1','Link 2', 'Link 3']"
          [animateIcon]="true"
          [dropdownCustomWidth]="'max-content'">
        </kn-icon-menu>`
       
        //here is the listener that is not working
       `let helpBtn = document.querySelector('#helpButton');`
        `helpBtn.addEventListener('btnClick', (e) => {
          console.log(e)
        });`

**Comment by MTobisch** [comment]
Hey there!

I'm not too well-versed in the details of Angular Elements or web components, but from the screenshot and code you've posted here, it seems that everything generally works. 

The dynamic `<kn-button>`-component is loaded, seems to accept and process its inputs fine and renders the inner #helpButton (as seen in the screenshot).

I wonder if its maybe just a async problem. As in, when you immediately do `document.querySelector('#helpButton')` after `masthead.rightNav = ...`, the help button might not even have rendered yet. Then a millisecond later, it is rendered and appears in the screenshot.

Maybe you could test this with `setTimeout` (or more safely via the `componentsLoaded` output of the `<ngx-dynamic-hooks>`-component)?

The duplication warnings are just warnings and I don't think they're the issue. Clearly, the `<kn-button>`-component is parsed and rendered. I'm not sure why it seems to the library that there are two parsers looking for the same hook. But like it says in the warning, in such a case the second one is just ignored and the first one processed normally, so it shouldn't affect functionality.

**Comment by knight3000** [comment]
@MTobisch Thank for the quick reply!

Two things worked, adding the timeout and changing the event listener to 'click'  instead of 'btnClick'. So I did need a delay. 

Another question I have. 

As you saw above, that component has three different spots where its using the dynamic hooks. I'm using three different variables for the context and content inputs. I'm trying to tie into the @output of the component which Ihave successfully done for other dynamically renders components however those only had one instance of dynamic hooks, where as this component has three. Can I use three different variables for "content" and "context". 

The code im using to interact with the component looks like this

`function helpBtnClick(e) {`
`   console.log(e.details);`
`}`

`const rightNavContext = { helpClick: this.helpBtnClick.bind(this)};`
`masthead.rightNavContext = rightNavContext;`

`masthead.rightNav =` 
`        '<kn-button `
`          [buttonId]="'helpButton'"`
`          [buttonType]="'kn-pill'" `
`          [buttonText]="'Help'" `
`          [buttonIconLeft]="'fa-regular fa-circle-question'"`
`          (btnClick)="rightNavContext.helpClick(e)">`
`        </kn-button>'`

Using that code, i get this error:

![image](https://github.com/MTobisch/ngx-dynamic-hooks/assets/12738683/bb980e1f-2368-4024-b59d-a7c62c96a8e7)

**Comment by MTobisch** [comment]
Sure, the `<ngx-dynamic-content>`-component has no idea what goes on in its parent component or how many other `<ngx-dynamic-content>`-components there are right next to it. You can use as many as you like.

Just from looking at it right now, the reason it throws the error is likely because you can't register to an output of a dynamic component with  `(btnClick)="rightNavContext.helpClick(e)"`. Try `(btnClick)="context.helpClick($event)` instead. 

**Explanation:** Within the dynamic content, there is always only one context (the one you passed to `<ngx-dynamic-content [context]="anyObjectYouLike">`). To access it from the content string, you then need to specifically use the `context` keyword. It doesn't matter what the context object was originally called. In a similar vein, if you want the event/output object passed to your listener, you also need to specifically use the `$event` keyword for the parameter.

**Comment by knight3000** [comment]
Wow! That did it! Thank you so much! It works great! This is a life saving plugin for sure.
