### ISSUE TITLE
Parsing encoded HTML entities fails

### ISSUE THREAD

**Issue by stpp2** [MTobisch/ngx-dynamic-hooks#35]
Hey,

Thanks for the great tool! It's really useful.

Looks like HTML entities like `&nbsp;` and so on aren't rendering as expected.
Repro: https://stackblitz.com/edit/ngx-dynamic-hooks-quickstart-3hyr1o?file=src%2Fapp%2Fapp.component.ts

Expected functionality should match Angular's `innerHtml` I suppose (which does render Ampersand / encoded HTML)

**Comment by MTobisch** [comment]
Hey there!

generally speaking, HTML entities should all render as their normal characters. There's even an option to turn that behaviour off in the [OutletOptions](https://github.com/MTobisch/ngx-dynamic-hooks#64-outletoptions)
