### ISSUE TITLE
Question: Can I use the content inside the tag as an input for my component?

### ISSUE THREAD

**Issue by Andrew-Marks-Trisept** [MTobisch/ngx-dynamic-hooks#40]
First off, thanks for this awesome library!

I'm trying to take user-generated markdown and display it in my app, allowing users to add in certain pre-defined components with a dedicated syntax.  For example, I want them to be able to easily insert one of my expansion panels with their desired header text and content text.

Example markdown string:
```
<markdown-expansion-panel heading="My _Cool_ Heading" content="My content with a **bold** word and...

...a second paragraph."></markdown-expansion-panel>
```

This uses the actual selector of my component and a couple inputs.  I convert the markdown to HTML and pass it to an `<ngx-dynamic-hooks>` tag, which causes my component to take the string from the `content` input and put it into an `[innerHtml]` attribute on a `div` inside my expansion component.  This all works great.

The problem is it's not very friendly for them to type, because you will end up with long, multi-paragraph text inside a quoted attribute.  I could also see a problem if they tried to use a `"` character in their text.

**Using a custom hook parser or something, is it possible to use the text _inside_ the hook tag as an input to my component?**

Something more like:

```
<expand heading="My _Cool_ Heading">
My content with a **bold** word and...

...a second paragraph.
</expand>
```

**Comment by MTobisch** [comment]
Hey there!

Yes, sure, that's mostly just using the normal transcluded content mechanism of Angular.

### Option 1 - Simple HTML

If the user markdown is already parsed to HTML and you just need to render it somewhere in your dynamic `ExpansionPanelComponent`, you can simply use the standard `<ng-content>` tag, which is a placeholder for any child elements that are passed to a component. Like so:

**Content string with finished HTML:**

```html
<expand heading="My _Cool_ Heading">
  <p>My content with a <b>bold</b> word and...</p>
  <p>...a second paragraph.</p>
</expand>
```

**ExpansionPanelComponent.html:**

```html
<div>
  <h1>{{ heading }}</h1>
  <div class="content">
    <ng-content></ng-content>
  </div>
</div>
```
### Option 2 - Raw Markdown

If the ExpansionPanelComponent is given the raw Markdown, you will have to add an extra step to intercept and parse it before rendering:

**Content string with raw Markdown (same you posted):**

```html
<expand heading="My _Cool_ Heading">
  My content with a **bold** word and...
  ...a second paragraph.
</expand>
```

**ExpansionPanelComponent.ts:**

```ts
export class ExpansionPanelComponent implements AfterViewInit {
  @Input() heading: string;
  @ViewChild('contentWrapper') contentWrapper: ElementRef;
  finalHtml: string;

  ngAfterViewInit() {    
    const rawMarkdown = this.contentWrapper.nativeElement.innerHTML;

    // Do optional markdown to HTML transformations here  
    const finalHtml = someFuncToParseMarkdown(rawMarkdown);

    // Then set finished html as a variable to render via innerHTML
    this.finalHtml = finalHtml;
  }
}
```

**ExpansionPanelComponent.html:**

```html
<div>
  <h1>{{ heading }}</h1>
    <div #contentWrapper class="content" style="display: none">
        <ng-content></ng-content>
    </div>

    <div [innerHTML]="finalHtml"></div>
</div>
```

Unfortunately, I'm not sure its possible to get the value of `<ng-content>` fully programmatically. I fear you need to render it at least once via `<ng-content>` in the component template. As you see in the example, I chose to simply hide it, but you might as well remove it after parsing the markdown.

**Comment by Andrew-Marks-Trisept** [comment]
Awesome!  Thanks again for your help and all your hard work on this.
