### ISSUE TITLE
Support for web components?

### ISSUE THREAD

**Issue by Andrew-Marks-Trisept** [MTobisch/ngx-dynamic-hooks#42]
I'm guessing this is a long shot, but is there any support for web components created via [Angular Elements](https://angular.io/guide/elements)?

I have a component where I'm using _ngx-dynamic-hooks_ and it works great on my site via the normal Angular build.  But I also do a second build where I wrap that component and define it as a custom element.  I end up with a .js file I can share with others and they can easily use my component on their site using the defined custom element, regardless of the technology they use.

When I test the generated web component like this, there is no error but the dynamic hooks portion doesn't output anything.  In fact, the `<ngx-dynamic-hooks>` element I typically see is not there at all.

**Comment by MTobisch** [comment]
Hm, this sounds indeed a bit puzzling. 

Unfortunately, I haven't tested the library in combination with Angular Elements as I had  assumed that they both do a similar enough job that you'd pick either one or the other (i.e. if a content string to render includes a selector like `<app-mycomponent>`, you could load the corresponding component either via this library or Angular Elements).

But even so, I don't see why it shouldn't work in a general way. The `<ngx-dynamic-hooks>`-component is a component like any other. So what's especially confusing is why it apparently disappears when rendering the web component. That's not happening to any other components in the template of the web component, I assume?

**Comment by MTobisch** [comment]
Hello again,

I've since looked into the topic more and tested the library with Angular Elements and found that it works fine for me!

I've created an minimal example project that uses the `<ngx-dynamic-hooks>`-component as part of a Angular Elements web component here: 

[https://github.com/MTobisch/angular-elements-with-dynamic-hooks](https://github.com/MTobisch/angular-elements-with-dynamic-hooks)

Maybe you can use it to help track down the error!

**Comment by Andrew-Marks-Trisept** [comment]
Thanks for the quick response!  I will need some time to investigate but I'll let you know what I figure out.

**Comment by Andrew-Marks-Trisept** [comment]
Thank you for the demo repo.  I can see it works fine there, but I still can't get it working for me.  We are doing several things differently, and I tried to figure out if any of them were causing the problem, including:

 - Using Shadow DOM viewEncapsulation vs default.

 - Standalone component vs modules.

 - Running the web component outside the Angular app instead of within it.  I tried to mimic what we do with your repo by doing a production build, copying the generated .js files, and using the web component directly in a simple .html page.

 - Differences in Angular version (16 vs 17) and builder (`@angular-devkit/build-angular:browser` vs`@angular-devkit/build-angular:application`).

 - Server-side-rendering.  We actually do some pre-rendering of certain routes, but doing a normal build without it didn't help.

I couldn't find anything that made a difference.  It always worked in your repo, but not in mine.  To try to narrow it down, I removed everything from the component I'm turning into a web component except for a simple test, like this:

```
<div style="border: 1px blue solid">
  <ngx-dynamic-hooks [content]="'Dynamic hooks test'"></ngx-dynamic-hooks>
</div>
```

Still didn't work.

----

Now, as mentioned, I use a sub-project and a separate build for generating my web component (i.e. there are two different projects in _angular.json_).  Building and running the normal Angular app works and ngx-dynamic-hooks works great.

Building the sub-project in production mode to generate the web component (like I usually do) finishes without errors and I can run the resulting web component on any HTML page.  However, if an `<ngx-dynamic-hooks>` element is in there, **it breaks its containing component entirely**.  The web component will be there with a `shadow-root` and everything, but the element for the component that contained the `<ngx-dynamic-hooks>` simply won't be in the DOM...

_Baseline test: Using a simple "Plain text test" `<span>` instead of `<ngx-dynamic-hooks>` to show where it should be._

![image](https://github.com/MTobisch/ngx-dynamic-hooks/assets/78372095/a43e78df-03c3-4ad2-ac43-320493484c9f)



_Test with `<ngx-dynamic-hooks>`:  Entire `<syn-header>` component is missing._ 

![image](https://github.com/MTobisch/ngx-dynamic-hooks/assets/78372095/3a6827d1-2e8d-450f-9a95-91afc74bae81)


There are no console errors, though.

----

But if I **serve** the sub-project instead of doing a production build, I finally see this error!

```
core.mjs:10614 ERROR NullInjectorError: R3InjectorError(AppModule)[OutletService -> OutletService]: 
  NullInjectorError: No provider for OutletService!
    at NullInjector.get (core.mjs:8890:27)
    at R3Injector.get (core.mjs:9334:33)
    at R3Injector.get (core.mjs:9334:33)
    at ChainedInjector.get (core.mjs:14018:36)
    at lookupTokenUsingModuleInjector (core.mjs:4608:39)
    at getOrCreateInjectable (core.mjs:4656:12)
    at Module.ɵɵdirectiveInject (core.mjs:11801:19)
    at NodeInjectorFactory.OutletComponent_Factory [as factory] (ngx-dynamic-hooks.mjs:258:118)
    at getNodeInjectable (core.mjs:4862:44)
    at instantiateAllDirectives (core.mjs:12629:27)
```

This appears to be a service defined within ngx-dynamic-hooks.  Any idea why this would happen?

I wish I could give you more to go on, but I've been unable to find the difference between your demo repo and my repo that is causing this.

**Comment by Andrew-Marks-Trisept** [comment]
Of course I figured it out five minutes after posting that long reply!  Since I have two projects, I forgot to do that `DynamicHooksModule.forRoot()` stuff in the second project's _app.module_.

Sorry for the false alarm!  Closing this.

**Comment by MTobisch** [comment]
I had just read your initial reply and immediately had that same suspicion. Went to test locally what error you would get if you omitted forRoot and sure enough, no OutletService provider. Right that moment I get an email that you closed the issue, haha.

Glad its all resolved, though!

**Comment by Andrew-Marks-Trisept** [comment]
Sometimes there are so many complicated things going on, you overlook the simple things...
