### ISSUE TITLE
contentChildren always array of 0 elements onDynamicChanges, onDynamicMount

### ISSUE THREAD

**Issue by andreazanti** [MTobisch/ngx-dynamic-hooks#6]
Hi! First of all thanks for all this great package. This saves me a lot of time and pain :)
I don't know if i've implemented in the wrong way or it is a problem due to a particular use case.
I'll try to explain me better:

- i have a pure html (request from an endpoint). This html has a certain tree structure of components , there are  some data attributes to understand which element/component the html portion represents

**HTML from the endpoint**
```
<div data-attribute-level1>
  <div data-attribute-level2>
       <div data-attribute-level3>
       </div>
  </div>
</div>
```

- I've used your FANTASTIC package to transform this pieces of html in angular components, maintaining the style from the html page, like in the emoji example but a lil bit more sophisticated. I've obtained the desired nested tree structure

**OUTPUT in angular:** 
```
- component level 1
    -  components level2 
        - components level3
```
        
        
All works very well. I have html of the portions linked to their business logic.

---------------------------------------------------------------------------------------------------

Now for each level in this tree structure i have, i need to have the ref to the children component
For example in the level1.component.ts i want to have the refs to all the level2 components.
I've read from your doc that i can use DynamicChanges and dynamicMount but they return always  contentChildren as array of zero elements. 

I'm maybe doing something wrong ?? 
Thanks a lot :)

**Comment by MTobisch** [comment]
Thank you for the kind words.

To be honest, I'm not sure why it doesn't work for you. Based on what you described here, the contentChildren should be passed in without problem. I've double checked that there isn't an issue with nested custom parsers somehow (I've even used `<div data-attribute-level1>` and `</div>` as the opening and closing tags of the hook), but it works fine on my end.

You say, you used the DynamicChanges and dynamicMount methods and that they "return" an empty array for contentChildren. I assume, you meant **on**DynamicChanges/**on**DynamicMount and did not call them yourself (they are called by the library when everything is loaded)?

Otherwise, if you could give me more information or, even better, a minimally reproducible version of your code (an example text, parser & component), i could probably pinpoint the issue for you.

**Comment by andreazanti** [comment]
Hi Man! Ok, this weekend i will try to pass you a reproducible code on stackblitz :)
Thanks in advance.

However, because there isn't a discussion section and i don't know how to contact you, i'd want to ask you another thing:
Do you have an example in which you pass not the root Injector in dynamic components?
I have a service injected in a dynamic component ( declared in the service provider, cause i don't want to be a singleton)
Some components below in the tree structure need to find this service ( the service injected in the first ancestor ), but the service is null. 
Infact from your documentation i see that you say that default Injector is root. How can achieve this?

**Comment by MTobisch** [comment]
I assume you mean that you [declared a service in the providers array of the decorator of your dynamic component](https://angular.io/guide/hierarchical-dependency-injection#elementinjector)? That should work normally, both for the parent component as well as all child components. I've actually just written a test to confirm. 

Note that it only works for ViewChildren though, not ContentChildren (so just for child components that appear in the template of their parent component, not child components that appear directly in the dynamic content string like: `<app-parent><app-child></app-child></app-parent>` and are transcluded into the parent's `<ng-content>`. That's just the standard Angular behaviour and my library actually isn't involved in that part at all - other than giving you the option to hand in your own injector for dynamic components.

If you still want to do that, creating a custom injector could look something like this: 

```
const CUSTOMSERVICETOKEN = new InjectionToken<any>('the token to identify your service by');
const customService = { name: 'this would be your service' };

const customInjector = Injector.create({
    providers: [{provide: CUSTOMSERVICETOKEN, useValue: customService }]
});
```

You then need to include this custom injector as part of a [SelectorHookParserConfig](https://github.com/MTobisch/ngx-dynamic-hooks#63-hookparserentry), or (when using a custom parser) as part of the [loadComponent-method](https://github.com/MTobisch/ngx-dynamic-hooks#loadcomponent). 

And then to get your service in a dynamic component: 
```
constructor(@Inject(CUSTOMSERVICETOKEN private customService : any) {}
```
