### ISSUE TITLE
Use SVG loaded from server as template

### ISSUE THREAD

**Issue by diogodomanski** [MTobisch/ngx-dynamic-hooks#7]
Hi @MTobisch ,

As you are the one who wrote this library, I think you are the right person to answer my question. :D

Is there a way to load a SVG content from server and set it as a component's template? 

For example, consider the following component:

```typescript
@Component({
    selector: 'my-component',
    template: `<ngx-dynamic-hooks [content]="mySvg"></ngx-dynamic-hooks>`
})
export class MyComponent {
    textColor: string;
    myText: string;
    mySvg: string;

    constructor() {
        this.textColor = '#ff0000';
        this.myText = 'Just testing';
    }

    loadSvg() {
        // here goes some logic to request the SVG string from server
       this.mySvg = response;
    }
}
```

Now, consider that the server returned the following string:

```svg
<svg>
    <tspan [attr.color]="textColor">{{myText}}</tspan>
</svg>
```

I would like the SVG to be rendered and the interpolations to work as well (making it possible to change the text and color).

Is it possible?

Thanks in advance

**Comment by MTobisch** [comment]
Hm, you could render a dynamic SVG of course, much like any other standard HTML element (though you will most likely have to [disable sanitization](https://github.com/MTobisch/ngx-dynamic-hooks#64-outletoptions) to persuade Angular to render it).

However, you can't load custom Angular template syntax like directives (attr.color) directly in the content string. Its unfortunately not something this library supports as the public Angular API only allows components (not directives) to be created dynamically. Sorry!

**PS:** This is probably a moot point now, but if you wanted to use variables in the content string for some other purpose (for example to use as inputs for the dynamically created components), you have to hand them in as context first. This would work like so:

```
@Component({
    selector: 'my-component',
    template: `<ngx-dynamic-hooks [content]="content" [context]="contextObj"></ngx-dynamic-hooks>`
})
export class MyComponent {
    content: string;
    contextObj: any = {
        textColor: '#ff0000',
        myText: 'Just testing'
    };
}
```
