### ISSUE TITLE
Empty string attributes as inputs (non-bracketed) 

### ISSUE THREAD

**Issue by tjwitz** [MTobisch/ngx-dynamic-hooks#9]
First off, thanks for this awesome project. 

I have found that when using non-bracketed inputs with an empty string value, the result is not an empty string, it is the string `'undefined'`.  Looks like the regex is pulling out an `undefined` value which is then wrapped in quotes here: https://github.com/MTobisch/ngx-dynamic-hooks/blob/b52b3414eecad96c1137485e7b3339e36fa5dd9f/projects/ngx-dynamic-hooks/src/lib/parsers/selector/services/bindingStateManager.ts#L57

I forked the example stackblitz and updated it with a few attributes on the dynamic content to demonstrate the issue precisely: https://stackblitz.com/edit/ngx-dynamic-hooks-quickstart-uuj6pb?file=src%2Fapp%2Fapp.component.ts

**Comment by MTobisch** [comment]
Thanks for noticing that!

I've gone ahead and fixed it in the new 1.7.1 release. Empty values from non-bracketed inputs will now properly result in empty strings.
